### ISSUE TITLE
No copyright posted

### ISSUE THREAD

**Issue by daniel-szulc** [Kubick-Rubick/angular-currency-converter#1]
Hi, I see you have duplicated my repository ([https://github.com/daniel-szulc/angular-currency-converter](url)) and made changes. As far as I can see, you have not included information about the source of the project. Please include copyright information.

**Comment by daniel-szulc** [comment]
As far as I can see, you still haven't mentioned me. Include project source information.

**Comment by Kubick-Rubick** [comment]
Yes man. My bad. I'm adding your copywriting the near future

пт, 23 груд. 2022 р. о 20:00 Daniel Szulc ***@***.***> пише:
